const UPDATE_TODOS = "UPDATE_TODOS";
const DELETED_TODOS = "DELETED_TODOS";
const STATUS_BTN = "STATUS_BTN";
const DONE_TODOS = "DONE_TODOS";
const IMP_TODO = "IMP_TODO";
const SEARCH_INPUT = "SEARCH_INPUT";
const EMPTY_TODO = "EMPTY_TODO";
const DELETE_ALL = "DELETE_ALL";
